### ISSUE TITLE
expiration defaults to standard keyboard

### ISSUE THREAD

**Issue by heyharvs** [vinaygaba/CreditCardView#14]
When gaining focus to the expiration field, the keyboard turns into a full keyboard.  Suggestion is to keep it as the numeric keyboard.

**Comment by vinaygaba** [comment]
Hi @heyharvs, 
This issue was fixed in v1.0.3 of the library. Use compile ‘com.vinaygaba:creditcardview:1.0.3’ and this should work as expected. I had not updated the readme file as I was trying to include more features in the release, but since it is taking time I'll push additional features to the next release.
